### ISSUE TITLE
Interactive mode

### ISSUE THREAD

**Issue by matthias-t** [mohd-akram/sw#2]
Please let me know if this is beyond the scope of this repo or not the use case of this crate, but what about adding a mode where the elapsed time is printed to the console and updated as it passes, with a keystroke to record a lap and one to stop?

**Comment by mohd-akram** [comment]
Thought about this a bit and couldn't think of a nice way to integrate it. However, I realized you can accomplish this with a short script:

```shell
#!/bin/sh
trap 'sw -1 elapsed | xargs printf "Time: %.2fs\n"; sw stop; exit' HUP INT TERM
sw start
while true; do
	printf "%.2f\r" `sw -1 elapsed`
done
```

Press `Enter` to record a new time and `Ctrl-C` to stop.

**Comment by matthias-t** [comment]
Wow that's really great, thanks!
